apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "simple-kubernetes-webhook.acme.com"
webhooks:
  - name: "simple-kubernetes-webhook.acme.com"
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: default
        name: simple-kubernetes-webhook
        path: /mutate-pods
        port: 443
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRekNDQWl1Z0F3SUJBZ0lVYWwrTklvNnFPRDZ4
        cWtIN21PQ1EzU09ybmVZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd01URUxNQWtHQTFVRUJoTUNRVlV4SWpB
        Z0JnTlZCQU1NR1hOcGJYQnNaUzFyZFdKbGNtNWxkR1Z6TFhkbApZbWh2YjJzd0hoY05Nak13TnpBMU1E
        a3hPVEk0V2hjTk1qUXdOekEwTURreE9USTRXakF4TVFzd0NRWURWUVFHCkV3SkJWVEVpTUNBR0ExVUVB
        d3daYzJsdGNHeGxMV3QxWW1WeWJtVjBaWE10ZDJWaWFHOXZhekNDQVNJd0RRWUoKS29aSWh2Y05BUUVC
        QlFBRGdnRVBBRENDQVFvQ2dnRUJBTmNkSWduSVVKbmErTUd0UGdoWk1NNjd0c0ZHMDVuegozdTN5Zkhl
        dEVRY05lS21jZmhOWnNyS3NvQWl3S2ZLWTg2UWdlamJnS0pKYU0wSThpSnBLWVp3S1F2MHpxWHk0Citl
        NDE5VGFqSUdQMkV0c1RicGVKMkRHQm1FUjMyOVZ5V2REVDB5Ym53SGRCdkQ5dkhWeHhRVEM2bHJicnox
        N2sKNk5GY3E2bnNERXVkNVhFUWlrZEtpSEhmZmtQNmdNMG5ja3pGUU04Nm5jb1lJUk1EclhtYll1U3FQ
        c1JkazVabgpOcThlanZlQmNhMDY5eVpGQm5zaFlPZE9CejkxVS9PSGdXMHNoSTM1UWd3UWlLTFRnV1No
        SjFuZG9zdnZiNXptCmU2aGZzcU9Yb2NIZ201VFhBQzI1WWlUd2Z4MVVvNHRnMWJkYzNOeHZieHpJWWhV
        VElxT2dZVXNDQXdFQUFhTlQKTUZFd0hRWURWUjBPQkJZRUZBeVVpd0dwcXJEd3lvUEFrNWVyc3RBaXV3
        YjJNQjhHQTFVZEl3UVlNQmFBRkF5VQppd0dwcXJEd3lvUEFrNWVyc3RBaXV3YjJNQThHQTFVZEV3RUIv
        d1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMCkJRQURnZ0VCQUMvK3ZNMnkvYzBBTC81cGtoMDFxQnpt
        LzNnK3p6OGg4dko5dnJsOStPa20weU9XRzZBQ1JrNEIKMmNZZmduZzlhMmlXd1NZbVNzbXlHK1BDMnpu
        bnFoa1pkQkcxekNkR2orMUJISDRSNE9pNHovOTliRFRQOXo5UAptSVpFbXY0SnZUM1A2WmplNWVzUFBP
        WWVyV3lKNFNZTWI1OGNCK2RwS216WlFjaGxhMjdyQXZEU1NpdmJGbllQCkNFOXRKTHgxTXZ6V3Bxa0lo
        dGRhVFQ1cFp4RXVPYzQ4ZHpJRXd1ZkdMdm50ZWpweXhid2FEbm5LNVdXcXhTWjkKb1RiNTBrditsdVF5
        ZHp5c1lYYVhkMXRiYS95bFpodi9Id1cwOHg1SzY0UW9VZ0h4MTllVVE5bHZ3aDF3TVg2RgpOeHgvbUVC
        RlFjUUwrcEtWOGt5WDF2Yng0V2NHUHBBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2
